// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace WTTech.Aem.Compose.Inputs
{

    public sealed class InstanceScriptArgs : global::Pulumi.ResourceArgs
    {
        [Input("inline")]
        private InputList<string>? _inline;

        /// <summary>
        /// Inline shell commands to be executed
        /// </summary>
        public InputList<string> Inline
        {
            get => _inline ?? (_inline = new InputList<string>());
            set => _inline = value;
        }

        /// <summary>
        /// Multiline shell script to be executed
        /// </summary>
        [Input("script")]
        public Input<string>? Script { get; set; }

        public InstanceScriptArgs()
        {
        }
        public static new InstanceScriptArgs Empty => new InstanceScriptArgs();
    }
}
