// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

// Export members:
export { InstanceResourceModelArgs } from "./instanceResourceModel";
export type InstanceResourceModel = import("./instanceResourceModel").InstanceResourceModel;
export const InstanceResourceModel: typeof import("./instanceResourceModel").InstanceResourceModel = null as any;
utilities.lazyLoad(exports, ["InstanceResourceModel"], () => require("./instanceResourceModel"));


const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "aem:compose:InstanceResourceModel":
                return new InstanceResourceModel(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("aem", "compose", _module)
