// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace WTTech.Aem.Compose.Outputs
{

    [OutputType]
    public sealed class InstanceScript
    {
        /// <summary>
        /// Inline shell commands to be executed
        /// </summary>
        public readonly ImmutableArray<string> Inline;
        /// <summary>
        /// Multiline shell script to be executed
        /// </summary>
        public readonly string? Script;

        [OutputConstructor]
        private InstanceScript(
            ImmutableArray<string> inline,

            string? script)
        {
            Inline = inline;
            Script = script;
        }
    }
}
