// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace WTTech.Aem.Compose.Outputs
{

    [OutputType]
    public sealed class InstanceModel
    {
        /// <summary>
        /// Version of the AEM instance. Reflects service pack installations.
        /// </summary>
        public readonly string Aem_version;
        /// <summary>
        /// A brief description of the state details for a specific AEM instance. Possible states include 'created', 'uncreated', 'running', 'unreachable', 'up-to-date', and 'out-of-date'.
        /// </summary>
        public readonly ImmutableArray<string> Attributes;
        /// <summary>
        /// Remote path in which AEM instance is stored.
        /// </summary>
        public readonly string Dir;
        /// <summary>
        /// Unique identifier of AEM instance defined in the configuration.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// A list of run modes for a specific AEM instance.
        /// </summary>
        public readonly ImmutableArray<string> Run_modes;
        /// <summary>
        /// The machine-internal HTTP URL address used for communication with the AEM instance.
        /// </summary>
        public readonly string Url;

        [OutputConstructor]
        private InstanceModel(
            string aem_version,

            ImmutableArray<string> attributes,

            string dir,

            string id,

            ImmutableArray<string> run_modes,

            string url)
        {
            Aem_version = aem_version;
            Attributes = attributes;
            Dir = dir;
            Id = id;
            Run_modes = run_modes;
            Url = url;
        }
    }
}
