# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .provider import *

# Make subpackages available:
if typing.TYPE_CHECKING:
    import wttech_aem.compose as __compose
    compose = __compose
else:
    compose = _utilities.lazy_import('wttech_aem.compose')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "aem",
  "mod": "compose",
  "fqn": "wttech_aem.compose",
  "classes": {
   "aem:compose:Instance": "Instance"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "aem",
  "token": "pulumi:providers:aem",
  "fqn": "wttech_aem",
  "class": "Provider"
 }
]
"""
)
