// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

export namespace compose {
    export interface ClientModelArgs {
        action_timeout?: pulumi.Input<string>;
        credentials?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
        settings: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
        state_timeout?: pulumi.Input<string>;
        type: pulumi.Input<string>;
    }

    export interface ComposeModelArgs {
        config?: pulumi.Input<string>;
        configure?: pulumi.Input<inputs.compose.InstanceScriptArgs>;
        create?: pulumi.Input<inputs.compose.InstanceScriptArgs>;
        delete?: pulumi.Input<inputs.compose.InstanceScriptArgs>;
        download?: pulumi.Input<boolean>;
        version?: pulumi.Input<string>;
    }

    export interface InstanceScriptArgs {
        inline?: pulumi.Input<pulumi.Input<string>[]>;
        script?: pulumi.Input<string>;
    }

    export interface SystemModelArgs {
        bootstrap?: pulumi.Input<inputs.compose.InstanceScriptArgs>;
        data_dir?: pulumi.Input<string>;
        env?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
        service_config?: pulumi.Input<string>;
        user?: pulumi.Input<string>;
        work_dir?: pulumi.Input<string>;
    }
}
