// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

export namespace compose {
    export interface ClientModel {
        action_timeout?: string;
        credentials?: {[key: string]: string};
        settings: {[key: string]: string};
        state_timeout?: string;
        type: string;
    }

    export interface ComposeModel {
        config?: string;
        configure?: outputs.compose.InstanceScript;
        create?: outputs.compose.InstanceScript;
        delete?: outputs.compose.InstanceScript;
        download?: boolean;
        version?: string;
    }

    export interface InstanceModel {
        aem_version: string;
        attributes: string[];
        dir: string;
        id: string;
        run_modes: string[];
        url: string;
    }

    export interface InstanceScript {
        inline?: string[];
        script?: string;
    }

    export interface SystemModel {
        bootstrap?: outputs.compose.InstanceScript;
        data_dir?: string;
        env?: {[key: string]: string};
        service_config?: string;
        user?: string;
        work_dir?: string;
    }

}
