name: Makefile

on:
  workflow_dispatch:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: docker://ghcr.io/pulumi/devcontainer:latest
      options: --user root
    permissions:
      contents: read
      packages: read
      actions: read
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      id: git
      with:
        submodules: 'recursive'
    - name: Unshallow clone for tags
      id: tags
      run: |
        sudo chown -R $(whoami) /__w/pulumi-aem/pulumi-aem
        git config --global --add safe.directory /__w/pulumi-aem/pulumi-aem
        git fetch --prune --unshallow --tags
    - name: Build
      id: build
      run: |
        make build
    - name: Test
      id: test
      run: |
        make test_provider
    - name: Install
      id: install
      run: |
        set -ex
        make install
